### ISSUE TITLE
New Relic startup error following the latest deployments

### ISSUE THREAD

**Issue by mnapoli** [mnapoli/externals#106]
@staabm I'm not sure it's caused by your code changes, maybe it's just something that changed on platform.sh in-between the occasional deployments.

> PHP Startup: newrelic: Unable to initialize module
> Module compiled with module API=20170718
> PHP    compiled with module API=20180731
> These options need to match

**Comment by staabm** [comment]
Hmm could be related to the php update (since different php versions have different module api versions).

Maybe the extension need to be updated

**Comment by mnapoli** [comment]
Yeah I'm tired of debugging platform.sh stuff, I'll remove the extension it wasn't even working anyway: #107

**Comment by mnapoli** [comment]
Thanks for having a look!

**Comment by staabm** [comment]
I did also some platform.sh debugging the last few days and can somehow agree that things are time consuming and harder to debug as usual :(
