### ISSUE TITLE
Encoding issue in email-content

### ISSUE THREAD

**Issue by SjonHortensius** [mnapoli/externals#11]
Pretty sure the person posting this didn't mangle his/her own name. It looks fine in the header.

http://externals.io/thread/378#email-12442

`Lauri KenttÃ¤`

**Comment by mnapoli** [comment]
Right thanks for the report, I've seen that a few times too. I haven't had time to look into more details for now. In the source the encoding is wrong too: http://externals.io/email/12442/source (click "view source"), so maybe it lacks some sort of decoding when retrieving the emails (in https://github.com/mnapoli/imapi). If you manage to debug anything further let me know, at the moment I'm swamped.

**Comment by DaveRandom** [comment]
I believe this issue will be fixed by the above referenced upstream PR.

**Comment by mnapoli** [comment]
This is deployed, let's see if it fixes the problem! Thanks @DaveRandom

**Comment by DaveRandom** [comment]
Looks good :-) https://externals.io/thread/786#email-14794

**Comment by mnapoli** [comment]
Awesome thanks!
