### ISSUE TITLE
New Thread not visisble on main page

### ISSUE THREAD

**Issue by SjonHortensius** [mnapoli/externals#111]
I just posted a message to internals which doesn't show on the homepage - see https://externals.io/message/104306

This might be caused by the fact that I forwarded this message from somewhere else - meaning it retained a 'bogus' `In-Reply-To` and `References` header.

**Comment by mnapoli** [comment]
Hi, this is highly probably that this is the cause indeed.

**Comment by SjonHortensius** [comment]
Okay, nice. It seems this was fixed in #59 but apparently that was not sufficient. Sorry for breaking it :(

**Comment by mnapoli** [comment]
No worries :) Unfortunately it's hard to handle all cases with email
