### ISSUE TITLE
Threads are broken more often recently

### ISSUE THREAD

**Issue by mnapoli** [mnapoli/externals#116]
It seems to me that threads do not show correctly more often than before lately.

I'd love to hear what other people think about this, it's been a few months since I haven't followed the latest discussions so I may be wrong.

Looking at threads in the home page many responses are not linked to the parent email, and it doesn't seem to affect only specific users…

**Comment by gharlan** [comment]
Especially many mails from Zeev, they do contain the `References` header. 
Example: https://externals.io/email/106370/source
I think the line after `MIME-Version: 1.0` is the `References` header, but it is broken, the beginning is missing.

Maybe we could also look at the `In-Reply-To` header when the `References` header is missing?

**Comment by mnapoli** [comment]
Right that is really annoying.

After looking a bit I think we should move entirely to using `In-Reply-To` instead of `References`.

Taking your example, here is the original thread: https://externals.io/message/101254 We have 2 problems:

- some emails are not linked to the original thread because `References` is missing
- some emails are in the thread (thanks to `References`), but are not *inside* the thread but rather at the root: this is because `References` points to the root, but `In-Reply-To` correctly points to the email the person was replying to

By moving to `In-Reply-To` we may be able to fix both problems at once.

The only question left: is `In-Reply-To` reliable and always available?

My stance would be to give it a try. The situation is far from ideal right now, it's worth taking risks.

What do you think?

**Comment by gharlan** [comment]
Yes, we can try. Maybe with fallback to `References` when `In-Reply-To` is missing?

**Comment by mnapoli** [comment]
Right, here is an example of a *very* old mail with no `In-Reply-To` : https://externals.io/message/2536#2784
