### ISSUE TITLE
RFC RSS links result in "Forbidden" response

### ISSUE THREAD

**Issue by ostrolucky** [mnapoli/externals#122]
Example links from feed at https://externals.io/rss-rfc: https://qlf0rokbdl.execute-api.eu-west-1.amazonaws.com/message/107370

Response: Forbidden

**Comment by PabloKowalczyk** [comment]
Same for me, looks like this line: https://github.com/mnapoli/externals/blob/master/src/RssRfcBuilder.php#L19, for some reason, do not return `externals.io`.
Maybe app is behind proxy?

**Comment by mnapoli** [comment]
> Maybe app is behind proxy?

That's correct. We could hardcode the real URL in this variable honestly, that would be much simpler.

If anyone is up for a PR I'd gladly merge it.

**Comment by PabloKowalczyk** [comment]
> We could hardcode the real URL (domain) in this variable honestly,

Sounds good to me. I could try to provide PR.

**Comment by orklah** [comment]
Nice to see it was fixed! Any idea when it will be deployed?

Thanks

**Comment by mnapoli** [comment]
Woops my bad! I just deployed right now, it seems to be OK. Let me know if something is wrong.

**Comment by orklah** [comment]
Cool! Thanks!
