### ISSUE TITLE
Update php requirements

### ISSUE THREAD

**Issue by gmponos** [mnapoli/externals#137]
Hey there..

I wanted to update the gravatar to use v2 of the package 

- https://github.com/gravatarphp/gravatar/releases/tag/v2.0.0
- https://github.com/gravatarphp/twig-integration (will tag v2 soon)

but I discovered that (according to composer.json file) the project is still running with min requirement as PHP of 7.1

Is there any reason? Anything I can help with to update.

**Comment by mnapoli** [comment]
The project is actually running on PHP 7.3 in production, so it's safe to update composer.json to 7.3.
