### ISSUE TITLE
Allow searching

### ISSUE THREAD

**Issue by alexbowers** [mnapoli/externals#14]
The ability to search titles and/or body content to get matching threads would be very useful.

It might be possible to get Algolia to sponsor this. I know they sponsor Laravel's docs searching

ping @maxiloc

**Comment by mnapoli** [comment]
Right Algolia would be perfect for that indeed. It's free for up to 10 000 records, which should be good for now (~3 000 emails) but won't last for long. If they can sponsor it that's great, it still requires to be coded though :).

**Comment by dzello** [comment]
Happy to look into this from the Algolia side (@maxiloc pinged me). Shoot me a note with what you think you'd need and we'll go from there? josh@algolia.com

**Comment by mnapoli** [comment]
@dzello that's awesome thanks! I'll try to work on that next week. The free plan will be enough to code the first version, I'll email you to check whether we can get a larger plan to ensure this is doable on the longer term.

**Comment by alexbowers** [comment]
Seems to have been implemented. Great :)

**Comment by mnapoli** [comment]
👍
