### ISSUE TITLE
Ui broken

### ISSUE THREAD

**Issue by staabm** [mnapoli/externals#145]
Not sure this happens because of the recent updates

![E52F264C-FFBE-40CD-928B-B0B30127EAA7](https://user-images.githubusercontent.com/120441/89103224-74a8b480-d410-11ea-9dfb-fc06ef44f70f.jpeg)

Experienced on ipad air, latest iOS

**Comment by mnapoli** [comment]
Yep I'm on it ^^

**Comment by mnapoli** [comment]
It should be good now, thanks for the report.

**Comment by staabm** [comment]
Confirmed, thx for the fix!

**Comment by mnapoli** [comment]
FYI we now have a status page ^^ https://status.externals.io/
