### ISSUE TITLE
Layout not ideal for deeply nested messages

### ISSUE THREAD

**Issue by gharlan** [mnapoli/externals#159]
https://externals.io/message/113419#113598

<img width="1246" alt="Bildschirmfoto 2021-03-18 um 10 37 38" src="https://user-images.githubusercontent.com/330436/111604884-13cec080-87d6-11eb-9af5-1e5a666871cf.png">

**Comment by francislavoie** [comment]
I came here to say this. I'd suggest removing the right gutter and making them full, and also reducing the left gutter by half. I'd also remove the bottom padding, it doesn't add much value IMO. Did some clicking around in the inspector, and I think it looks good like this (obviously the content of these classes shouldn't change, but the actual classes used should be the smaller sized ones from Tailwind -- easier to demo it like this in the browser than updating all the classes on every element)

![image](https://user-images.githubusercontent.com/2111701/111652651-9f981b00-87dd-11eb-8de1-4be8ca2969e7.png)

![image](https://user-images.githubusercontent.com/2111701/111652735-b2aaeb00-87dd-11eb-83dc-b6828f883d3c.png)

![image](https://user-images.githubusercontent.com/2111701/111652792-bf2f4380-87dd-11eb-85b2-665be2b32c6e.png)

**Comment by gharlan** [comment]
fixed via #160, thanks!
