### ISSUE TITLE
Algolia Logo Low Res

### ISSUE THREAD

**Issue by alexbowers** [mnapoli/externals#16]
![image](https://cloud.githubusercontent.com/assets/842974/21594736/0a170246-d11e-11e6-84d9-eba123cfd2ff.png)

Using a 5k imac, the image is pretty low res. Perhaps a 2x image is necessary?

**Comment by mnapoli** [comment]
👍  agreed, I couldn't find a good source for the logo, maybe @dzello can help us? I spent like 15 minutes searching online for the logo with transparent background but found nothing :(

**Comment by alexbowers** [comment]
SVG here: https://github.com/algolia/algolia.github.io/blob/master/img/logo-algolia.svg

**Comment by alexbowers** [comment]
Colours are wrong, but that can be easily modified using Illustrator

**Comment by mnapoli** [comment]
Right white on white won't do, I don't have Illustrator, if you or anyone else wants to send a pull request I'd gladly merge this.

**Comment by dzello** [comment]
Here's a black SVG. It doesn't have the "by" but we could add that with CSS. I'll also check with our designers to see if we can make an SVG version with the "by".

![https://d17oy1vhnax1f7.cloudfront.net/items/2e3P3q3P0p051r0y0n3D/logo-algolia-bw-nobg.svg](https://d17oy1vhnax1f7.cloudfront.net/items/2e3P3q3P0p051r0y0n3D/logo-algolia-bw-nobg.svg)

**Comment by alexbowers** [comment]
@dzello Can we perhaps also get a "media" page on the algolia website where we can access these images from and see previews? Finding them in a midst of 6 pages on GitHub was pretty tricky

**Comment by alexbowers** [comment]
I stand corrected; there is one: https://www.algolia.com/press#resources

**Comment by alexbowers** [comment]
Another SVG to consider https://www.algolia.com/static_assets/images/press/downloads/powered-by-algolia.svg

**Comment by alexbowers** [comment]
Or this: https://www.algolia.com/static_assets/images/press/downloads/algolia-light.svg

**Comment by dzello** [comment]
Yeah, it's not fun to have to hunt around, we're planning to make that resources page more visible and put more assets on it. Personally I'm a fan of the black-only version for this site. That "powered by" logo is a little out of date and long horizontally. Today is a holiday but I'm hoping to hear back from our designers tomorrow to see what they recommend.

**Comment by Shipow** [comment]
Hi there, we are in the process of releasing a dedicated page for that purpose. We made a refresh of the logo, sorry for the inconvenience. 
Here is the link to the latest version: https://www.dropbox.com/s/0mgi1si3czgghyw/search-by-algolia.svg?dl=0
Let us know if everything is okay for you!

**Comment by staabm** [comment]
@Shipow any news regarding the latest logo... I am willing to incorporate into externals.io

**Comment by Shipow** [comment]
you can use this one, it's safe :p

https://www.dropbox.com/s/zvfwws2pwp6sbjh/search-by-algolia.svg?dl=0

**Comment by staabm** [comment]
thx

**Comment by staabm** [comment]
thx
