### ISSUE TITLE
A couple recent emails are missing

### ISSUE THREAD

**Issue by francislavoie** [mnapoli/externals#176]
https://news-web.php.net/php.internals/118991 and https://news-web.php.net/php.internals/118992 don't seem to show up 🤔

Do you have anything in the logs that show a problem with those?

**Comment by mnapoli** [comment]
Interesting 🤔 

They seem to work fine in threads: https://externals.io/message/118991

And they are indexed in search as well:

<img width="940" alt="image" src="https://user-images.githubusercontent.com/720328/201526014-6be541f9-8d7c-4761-9f9c-aedc166e15ae.png">

Nothing specific in the logs, the execution succeeded:

<img width="1600" alt="image" src="https://user-images.githubusercontent.com/720328/201526277-5367ee56-990a-4216-9dde-2876eb7f3c22.png">

I wonder why they don't show up on the home page.

**Comment by francislavoie** [comment]
Alright well I guess I'll close this :man_shrugging: unsolved mystery for now I guess.
