### ISSUE TITLE
New messages don't appear

### ISSUE THREAD

**Issue by kelunik** [mnapoli/externals#18]
It seems like the message from the last two days do not appear.

**Comment by mnapoli** [comment]
Hi, thanks for the report. It seems you are correct, I logged in the email address that receives all internal emails and there's nothing after 1st of january (so it seems it's not a problem with the PHP application). I don't have time to look at it right now, maybe it's a temporary problem with PHP's mailing list? I'll wait a few days, if you see any information about that it will be welcome.

**Comment by kelunik** [comment]
Indeed, @bwoebi just told me that php.net is still broken.

**Comment by mnapoli** [comment]
Thanks!
