### ISSUE TITLE
Avatars from "unavatar" no longer seem to work

### ISSUE THREAD

**Issue by francislavoie** [mnapoli/externals#182]
I'm getting 404s from image requests to https://unavatar.vercel.app

I think https://unavatar.io should be used instead, now. That one seems to work from a quick Google search.

Edit: Oh rather `unavatar.now.sh` is being used currently, which triggers redirects to `unavatar.vercel.app`. But `unavatar.io` seems to work now.

**Comment by mnapoli** [comment]
Thanks for the detailed summary! I'd gladly merge a PR if anyone wants to implement that change!
