### ISSUE TITLE
PHP Externals Site Not Updating

### ISSUE THREAD

**Issue by ghostwriter** [mnapoli/externals#191]
Hello,👋🏾

I hope this message finds you well.

I wanted to bring to your attention an issue with the PHP externals site.

It appears that the site has stopped updating, as the newest message displayed is from five days ago.

However, there are newer messages available on the PHP internals site.

Thank you for your time and consideration, your work is greatly appreciated.

Have a great weekend.✌🏾

**Comment by mnapoli** [comment]
Hey, thanks for bringing this up!

Indeed everything started failing 3 days ago with the following exception:

```
[INFO] Synchronizing message 121607
10/11/2023 21:32:38
a10bb261-cf74-44f9-8d3c-21906439e62f	Invoke Error	{...}
{
  "errorType": "Rvdv\\Nntp\\Exception\\SocketException",
  "errorMessage": "",
  "stack": [
    "#0 /var/task/vendor/rvdv/nntp/src/Connection/Connection.php(152): Rvdv\\Nntp\\Socket\\Socket->gets()",
    "#1 /var/task/vendor/rvdv/nntp/src/Connection/Connection.php(108): Rvdv\\Nntp\\Connection\\Connection->getMultiLineResponse()",
    "#2 /var/task/vendor/rvdv/nntp/src/Client.php(212): Rvdv\\Nntp\\Connection\\Connection->sendCommand()",
    "#3 /var/task/src/EmailSynchronizer.php(78): Rvdv\\Nntp\\Client->sendCommand()",
    "#4 /var/task/src/Application/Handler/SynchronizeHandler.php(18): Externals\\EmailSynchronizer->synchronize()",
    "#5 /var/task/vendor/bref/bref/src/Runtime/Invoker.php(29): Externals\\Application\\Handler\\SynchronizeHandler->handle()",
    "#6 /var/task/vendor/bref/bref/src/Runtime/LambdaRuntime.php(102): Bref\\Runtime\\Invoker->invoke()",
    "#7 /opt/bref/bootstrap.php(43): Bref\\Runtime\\LambdaRuntime->processNextEvent()",
    "#8 {main}"
  ]
}
```

There are no details in the exception.

I can see two possibilities:

- message 121607 is broken/breaking the system somehow (that is very rare but [has happened before](https://github.com/mnapoli/externals/blob/master/src/EmailSynchronizer.php#L31-L38))
- the mailing list server is offline?

Any idea what could be going on?

**Comment by mnapoli** [comment]
OK I think it's the message itself that is a problem, the web page for this message doesn't load: https://news-web.php.net/php.internals/121607

I've pushed a commit to ignore that message, let's see.

Thank you for bringing this up!

**Comment by ghostwriter** [comment]
Looking through the list https://news-web.php.net/php.internals/start/121606, the issue might be caused by the date of the email.

(121607: `Thu, 01 Jan 1970 00:00:00 +0000`)

Thanks for addressing this matter.
