### ISSUE TITLE
Use NNTP instead of IMAP?

### ISSUE THREAD

**Issue by heiglandreas** [mnapoli/externals#3]
As far as I see it you are currently grabbing the Emails from the Mailinglist.

What was the reason to not use the nntp-Interface on news.php.net?

**Comment by mnapoli** [comment]
I'd happily use a cleaner method. Right now I have an email address subscribed to the mailing list, and I fetch the latest emails through IMAP. How would you use that nntp interface with PHP?

**Comment by heiglandreas** [comment]
Now that I look at it, I've realized that I didn't ever use PHP to handle NNTP. I've always used NNTP-Clients. 

But there is a [library on packagist](https://packagist.org/packages/rvdv/nntp) that looks promising. The examples even use the PHP news-server :wink:

**Comment by mnapoli** [comment]
Oh that's interesting, I think this is the first time I see that library. I'll see if I can give it a try soon, the advantages I see are:

- no reliance on a personnal free email address (that could disappear anyday)
- easier for contributors to get data to make the website work locally
- maybe I can access more information that way (e.g. the same IDs as in the URLs here: http://news.php.net/php.internals/94447)
- maybe allows search, or listing by date range (would allow to get back in the past much further, and on demand)
- allows to post messages

**Comment by heiglandreas** [comment]
Posting new messages sadly won't work due to the limitations of that specific news-server implementation. :frown:

**Comment by mnapoli** [comment]
I've started to work on that and most of the work is done.

There are many advantages to that:

- all the messages in PHP's history will be fetched and indexed for search \o/
- synchronization will be much simpler, reliable and faster too I think
- the whole system will be much more solid (it won't rely on some random email address subscribed to the mailing list -> if I loose the email address the whole site is dead)
- it will be easier to setup a dev environment and fetch the last X messages
- re-deploying to a new server will be easy (I want to migrate to another server, and also that's a good thing in case the server dies)

I'm stuck on a big problem though, if anyone knows a bit about NNTP (or PHP's NNTP servers) help would be really appreciated: https://github.com/robinvdvleuten/php-nntp/issues/31 (blank lines are dropped from messages)

**Comment by heiglandreas** [comment]
I'd love to see a hex-dump of this message. As CRLF has a special meaning in NNTP and SMTP it'd be interesting to see what characters are actually sent there! 

And does that problme exist with all messages or only with some?

**Comment by heiglandreas** [comment]
Ignore the last comment. Phone-interface isn't tgat good and I commented on the wrong issue...
