### ISSUE TITLE
App down?

### ISSUE THREAD

**Issue by staabm** [mnapoli/externals#30]
https://externals.io/ Seems to be down

**Comment by mnapoli** [comment]
Thanks I'm looking into that, I had problems this morning too but I thought that was all fixed :/ It seems it's not.

**Comment by mnapoli** [comment]
@staabm it should be up now, I had a very weird issue with Puli. Can you confirm it works fine for you?

**Comment by mnapoli** [comment]
OK nevermind it's down again, that's more serious than I thought :'(

**Comment by mnapoli** [comment]
It turns out it was the fault of dynatrace.com I installed it this morning to try it out but that clearly wasn't a success :/

Sorry about that, it seems to be working fine now!

**Comment by staabm** [comment]
Confirmed, works again! Thx man.
