### ISSUE TITLE
Too much white space in new design

### ISSUE THREAD

**Issue by staabm** [mnapoli/externals#35]
The newly added design feels not good on iPad.

The most important information - the list contents itself - is not actually shown in the first view.
The inital page contains too less threads IMO and too much header

Landscape View
![img_0993](https://user-images.githubusercontent.com/120441/27841368-c69ad768-6100-11e7-895a-0fad3082b99f.PNG)

Portrait View
![img_0994](https://user-images.githubusercontent.com/120441/27841369-c6cb2cc4-6100-11e7-9d9e-cdce0c0aafde.PNG)

**Comment by mnapoli** [comment]
Thanks for the feedback, I'll fix this soon, I'm working on a redesign. Funnily enough the new design has even more space so I'll try to contain myself and remove some instead ;)

Will be done in #34

**Comment by staabm** [comment]
On regular desktop - with enough screen estate - the whitespace is ok IMO, maybe limit it with a media query to a certain resolution/densitiy

**Comment by staabm** [comment]
Hmm on aphone its even worse:-/

![img_5560](https://user-images.githubusercontent.com/120441/27967583-dd56ae24-6343-11e7-98de-c794106f5934.PNG)
![img_5559](https://user-images.githubusercontent.com/120441/27967600-f4c9acbe-6343-11e7-9d16-cd184eba384d.PNG)

**Comment by mnapoli** [comment]
It was closed when I merged but v2 is not deployed yet, there has been no changes deployed for now.

**Comment by mnapoli** [comment]
I'm still processing the 100 000 emails from #internals

**Comment by mnapoli** [comment]
Forgot to close this issue!

![img_3815](https://user-images.githubusercontent.com/720328/28492942-bb00f6a2-6f0c-11e7-802d-9ed23a4e06ce.PNG)
