### ISSUE TITLE
Favorites/Upvote system

### ISSUE THREAD

**Issue by mnapoli** [mnapoli/externals#37]
I'm wondering if a system of "favorites" or "upvote/downvote" system could be useful in threads.

The thing is that there is a bit of noise in the thread list (e.g. all the "benchmark" emails) and there are some very interesting discussions. It's hard to find what's interesting to follow, either you have to read the mailing list daily and read most threads, either you can't follow #internals.

An upvote/downvote system would allow to

- hide/deprioritize uninteresting threads (remove noise)
- mark the most interesting threads

Just like in Reddit users could then read the most interesting threads of the last week, month, year. That could also allow to find interesting threads in the whole history of internals (important discussions, votes, RFCs, etc.).

Such ratings could also be used for search results: for example if you search for "strict types RFC" you could then find the original threads.

What do you think?

**Comment by staabm** [comment]
I agree this could be usefull.
