### ISSUE TITLE
Login redirects to externals.io even on PR preview deployments

### ISSUE THREAD

**Issue by staabm** [mnapoli/externals#38]
Just played arround on https://master-7rqtwti-2snxbat5vggso.eu.platform.sh/ with the new version.

It seems I am getting redirected to externals.io (production website) when clicking the login.
This could make testing hard of other features later on when people dont realise it

**Comment by mnapoli** [comment]
Yes that's what I told you in https://github.com/mnapoli/externals/commit/90c597a04e87158dedc8332020cfb948ad0a73e2#commitcomment-22989755 ;)

I need to test that and then I'll probably switch to production, there will be no point in fixing that in the long run since this URL will disappear.

**Comment by staabm** [comment]
As I read in 'whats new' that PR will be deployed to a instance which makes them instantly testable, I guess fixing that for those snapshot deployments it should be fixed...?

**Comment by mnapoli** [comment]
Yes I spent a few hours trying to make it work but it seems GitHub doesn't allow overriding the "return_url" for oauth. So I need to create a new "oauth application" for every branch.

I'm doing it for #44 but I need to do that manually every time (unless I take the time to implement some sort of workaround, e.g. a "magic login" link that works only in staging)
