### ISSUE TITLE
Move "search by angolia" into the search field when space allows

### ISSUE THREAD

**Issue by staabm** [mnapoli/externals#39]
Atm the "search by angolia" label occupies a horizontal line on its own. It would be great when this label could stand e.g. Side by side with the input text field or alternatively would cover the field on the right side, to save this space.

On mobile or other very small screens the current solution should stay as is though, to have enough space to input a search term
![img_0996](https://user-images.githubusercontent.com/120441/27992138-acb2e004-648c-11e7-9d8a-a744ceb981aa.PNG)

**Comment by mnapoli** [comment]
The link is necessary for the partnership with Algolia, I tried a lot of different options but this is working fine for me. Feel free to try with pull request but I fear this would take some time again to find a good solution.
