### ISSUE TITLE
Rewrite links to http://news.php.net/php.internals

### ISSUE THREAD

**Issue by staabm** [mnapoli/externals#4]
People link to older message/threads with links like http://news.php.net/php.internals/93662 .

We could rewrite those links to point to externals.io links to not jump between different internals webinterfaces.

See e.g. http://externals.io/thread/110#email-10562

**Comment by mnapoli** [comment]
I'm not sure I understand what you suggest, I cannot change what `news.php.net` does?

**Comment by staabm** [comment]
But couldnt you rewrite the link to point to externals.io instead?

**Comment by mnapoli** [comment]
Ah OK, indeed it's possible, it should be easy to do with a regex replace. Can you send a pull request for that?

**Comment by mnapoli** [comment]
Closing this feature request too, I'm happy to merge contributions.
