### ISSUE TITLE
favicon

### ISSUE THREAD

**Issue by staabm** [mnapoli/externals#51]
just discussed on room11 that it would be great to have a favicon for this tools (to make it easier to identifiy the tab in the browser).

we though something like a "#e" symbol could be usefull... any idea/input from your side @mnapoli ?

**Comment by mnapoli** [comment]
That's a good idea! Here is a suggestion (after a dozen tries ;) ): https://externals.io/

**Comment by staabm** [comment]
Cool, should also be added as mobile-touch-icon and we are finished.

Tank you

**Comment by staabm** [comment]
@mnapoli already felt in love with the new logo. it shows up everytime when open a new tab/window in firefox <3

**Comment by mnapoli** [comment]
:D very happy to know that!
