### ISSUE TITLE
use proper http caching headers

### ISSUE THREAD

**Issue by staabm** [mnapoli/externals#54]
atm we send `cache-control: no-cache` with main.min.css and main.min.js, which means this files are re-transmitted on each page load.

as the urls to this resources contain a cache buster parameter, we should instead use the opposite: a very long max-age at best in combination with the `immutable` flag, which tells the browser to not reload the file even on hard-refresh.

`Cache-Control: max-age=31536000, immutable` would be the way to go - at least for this 2 files.

**side-note**: it seams externals css/js from algoliasearch/instantsearch etc. seem to have proper cache headers already (because those are fetched from jsdelivr)

**edit**: also the webfont.woff2 file should use this headers. those 3 assets are in the top 4 of assets when filesize is a concern.

**Comment by mnapoli** [comment]
Good point, it seems this could be solved using the `expires` key in `.platform.app.yaml`: https://docs.platform.sh/configuration/app/web.html#locations

If you want to give it a try you can open a pull request: after a few minutes Platform.sh will deploy the pull request (the link will be set as a "green" build status for the PR). You can then check on the deployed environment that the headers are set.

**Comment by mnapoli** [comment]
Good point, it seems this could be solved using the `expires` key in `.platform.app.yaml`: https://docs.platform.sh/configuration/app/web.html#locations

If you want to give it a try you can open a pull request: after a few minutes Platform.sh will deploy the pull request (the link will be set as a "green" build status for the PR). You can then check on the deployed environment that the headers are set.
