### ISSUE TITLE
mixed content errors

### ISSUE THREAD

**Issue by staabm** [mnapoli/externals#56]
when loading https://externals.io I can see mixed content errors in the firefox dev-console

![grafik](https://user-images.githubusercontent.com/120441/32594136-1b9ff00c-c52b-11e7-8a98-e0d2e67b9ec9.png)

I did not further check when/where those resources are referenced

**Comment by mnapoli** [comment]
Do you have an extension that could be loading these? Because I don't think those are included by the website itself.

**Comment by staabm** [comment]
I dont think so

**Comment by mnapoli** [comment]
What I meant is that I don't see those HTTP requests on my machine, externals.io does not load them. It must come from elsewhere?

**Comment by staabm** [comment]
hmm I guess its either a bug in firefox or one of my extensions. I can see strange x-origin requests also on other websites.
