### ISSUE TITLE
Non-threaded view?

### ISSUE THREAD

**Issue by dcelasun** [mnapoli/externals#6]
Is it possible to add a non-threaded view, simply sorted by date in ascending order? It would make following who posted what and when much easier.

**Comment by mnapoli** [comment]
Hi! It would be possible but the question is "how to make it usable?" Right now there are no settings stored for users (and no "profile configuration" page), so you would have to click on some link ("view non-threaded") for every discussion, which is kind of boring. Anyway I'm open to merging a pull request that adds this cleanly.

Cheers!
