### ISSUE TITLE
Internals news feed not working?

### ISSUE THREAD

**Issue by bronek89** [mnapoli/externals#67]
Hi,

It seems that http://news.php.net/php.internals/ page does not working, neither direct news group downloading nor externals.io. Last update on externals is from 12 days ago.

Do you know what's going on with php internals group?

**Comment by mnapoli** [comment]
Nikic explained on Reddit that there is a problem currently with the news server: https://fr.reddit.com/r/PHP/comments/99w2xs/is_externals_broken/e4qtwgo/

I don't know what to do except wait it out :/

**Comment by bronek89** [comment]
They working on that - https://twitter.com/rasmus/status/1033937569807982592 :)

Thank you for info

**Comment by staabm** [comment]
The news server is back again, issue resolved?

**Comment by bronek89** [comment]
For me it's good now :)
