### ISSUE TITLE
Support for other lists?

### ISSUE THREAD

**Issue by PeeHaa** [mnapoli/externals#7]
Will support of [the other lists](http://news.php.net/) be within the scope of this project or will it be just for internals?

**Comment by mnapoli** [comment]
It's indeed probably out of the scope, do you have a specific list in mind?

**Comment by PeeHaa** [comment]
All of them :P

**Comment by mnapoli** [comment]
Then no :) it's not the goal of this project (but forking that might be a good start)

**Comment by PeeHaa** [comment]
Yeah that was my next step. Just wanted to make sure we weren't going to work on the same things.

Like the service btw!
