### ISSUE TITLE
Use svg icons instead of font awesome

### ISSUE THREAD

**Issue by staabm** [mnapoli/externals#76]
Icon font are considered bad practice nowadays. Furthermore within this app we use only very few of the icons within the font, therefore overhead is very big.

We should either consider extracting the icons/self host the icons or use some similar free licensed images as a replacement, so FA is no longer required.

See 
https://www.webpagetest.org/result/180907_6C_9abf7ebd4000568651e24bb3bfc7008a/1/details/#waterfall_view_step1 for the speedimpact of font awesome
- css file is big because of fa-styles import
- dom interactive is very late because of font loading

**Comment by staabm** [comment]
will be implemented in https://github.com/staabm/externals/tree/fa-svg

**Comment by mnapoli** [comment]
Done in #156
