### ISSUE TITLE
Variable font instead of several fonts per font-weight

### ISSUE THREAD

**Issue by staabm** [mnapoli/externals#80]
Right now we need to load a font file per used font-weight/style.

Since FF latest version added support for variable fonts, all major browsers support it now.
We should check whether there is a free licensed variable font available which matches our expected visuals and load this single font instead of what we have right now

**Comment by staabm** [comment]
would/could https://v-fonts.com/fonts/source-sans-variable work ?

**Comment by mnapoli** [comment]
It seems to be the same font as Open Sans but variable (which I just discovered existed ^^) so I guess if it works then that's great yes!

**Comment by staabm** [comment]
It seems the variable font would only be worth it, when a lot of different page weights are used.

Atm we use only a few. Also I would love to get rid of some of them so we can use less regular font files
