### ISSUE TITLE
Serve http://externals.io over TLS

### ISSUE THREAD

**Issue by PeeHaa** [mnapoli/externals#9]
Could you set up the domain to be served over TLS please?

**Comment by mnapoli** [comment]
👍  that would be great indeed, I think it might be a bit of work (I'm not familiar with that). I'll have a look but I can't promise anything right now.

**Comment by PeeHaa** [comment]
What do you need help with? I am happy to help out.

**Comment by mnapoli** [comment]
Oh wait I could use Cloudflare! I remember enabling it on https://isitmaintained.com/ and it works well, I didn't have a single thing to do except clicking a button (and it's free).

**Comment by mnapoli** [comment]
I've setup Cloudflare and enabled HTTPS, it says it could take up to 24h so let's wait and see!

**Comment by mnapoli** [comment]
It works!

**Comment by PeeHaa** [comment]
Nice \o/ Thanks!
