### ISSUE TITLE
close old PRs

### ISSUE THREAD

**Issue by staabm** [mnapoli/externals#90]
I guess the deployment of new PRs to a dev environment on plattform.sh doesnt work, because some old PRs occupy the available instances.

I remember @mnapoli mentioned there are 3 available slots.

see

![grafik](https://user-images.githubusercontent.com/120441/45502381-22127080-b784-11e8-88d7-93e0c2d66f89.png)

**Comment by mnapoli** [comment]
I've closed one for now, I want to try #66 at some point because it seems like an interesting PR but it could break things in a very silent way, so it's hard to be confident :/

**Comment by staabm** [comment]
thx!

**Comment by staabm** [comment]
for the record: platformsh confirmed there are known problems with the github integration atm:
https://twitter.com/Crell/status/1040606744601341952
