### ISSUE TITLE
streamline the ui and its assets (code weight)

### ISSUE THREAD

**Issue by staabm** [mnapoli/externals#95]
our app is rather small and layout is not so complicated.

we should consider
- [ ] getting rid of bootstrap and use flexbox/css-grid/... natively
- [ ] alternatively: use a smaller footprint lib
- [ ] self host the used google fonts

that way this should reduce request size of our main.js and main.css files, which are rather big right now:

![image](https://user-images.githubusercontent.com/120441/45583833-517ec580-b8c9-11e8-81ce-780ec8162abf.png)

resources which might help guide our way
https://blog.theodo.fr/2018/03/stop-using-bootstrap-layout-thanks-to-css-grid/
https://www.reddit.com/r/webdev/comments/3sjiv7/how_to_move_away_from_depending_on_bootstrap/

**Comment by staabm** [comment]
just an update. per chrome "coverage" feature ~95% of main.css and 74,2% of main.js is unused on the homepage

![grafik](https://user-images.githubusercontent.com/120441/52415532-7fb6a900-2ae7-11e9-98d2-145fc1b7ace9.png)

see https://blog.logrocket.com/using-the-chrome-devtools-new-code-coverage-feature-ca96c3dddcaf on how to get to this coverage numbers

**Comment by staabm** [comment]
@mnapoli I guess you might consider a Bref based rewrite for externals.io

In case - will the ui stay the same - so my time is not wasted for squeezing out more performance out of it?

**Comment by mnapoli** [comment]
@staabm yes the UI would stay the same, it would only be a rewrite for the PHP part.

**Comment by mnapoli** [comment]
I think #156 addresses some points here: I've dropped the custom font and bootstrap and font awesome. I now use tailwind and purge any unused CSS before deploying.
The only dependency left is jQuery, I'm sure we'll be able to get rid of that eventually.

**Comment by staabm** [comment]
yeah, looks like it will use better assets. thx for getting back to it.
